In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from myutils import *

In [3]:
train_data = pd.read_csv('Dataset/processed/train_processed/recoded_train.csv')
test_data = pd.read_csv('Dataset/processed/test_processed/recoded_test.csv')
train_data.head()
feature_json = read_jsonl('config/feature.json')
feature_config = feature_json['features']

In [4]:
test_data.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,glyburide,pioglitazone,rosiglitazone,insulin,change,diabetesMed,readmitted,diag_1,diag_2,diag_3
0,2.0,0,0,NaN,NaN,0.0,1,NaN,37.0,41,...,1,1,1,1,1,0,2,4,NaN,NaN
1,0.0,0,4,0.0,0.0,12.0,9,NaN,NaN,47,...,1,1,1,2,1,1,1,4,1.0,5.0
2,NaN,0,5,1.0,0.0,9.0,2,NaN,NaN,66,...,1,1,1,0,0,1,2,1,1.0,1.0
3,0.0,0,6,0.0,0.0,12.0,6,NaN,NaN,87,...,3,1,1,2,0,1,2,7,2.0,4.0
4,2.0,0,7,0.0,8.0,12.0,1,NaN,3.0,28,...,1,1,1,0,0,1,1,1,1.0,4.0

In [5]:
features = train_data.columns.tolist()
for feature in features:
    if feature_config[feature]['type'] != 'categorical':
        continue
    train_vc = train_data[feature].value_counts()
    test_vc = test_data[feature].value_counts()
    train_unique = train_data[feature].unique()
    test_unique = test_data[feature].unique()
    for tu in test_unique:
        if tu not in train_unique:
            print(f'{feature} {tu} not in train')
    print('-'*100)

race nan not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
admission_type_id nan not in train
----------------------------------------------------------------------------------------------------
discharge_disposition_id nan not in train
----------------------------------------------------------------------------------------------------
admission_source_id nan not in train
----------------------------------------------------------------------------------------------------
payer_code nan not in train
----------------------------------------------------------------------------------------------------
medical_specialty nan not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
diag_2 nan not in train
----------------------------------------------------------------------------------------------------
diag_3 nan not in train
----------------------------------------------------------------------------------------------------

In [9]:
train_data = pd.read_csv('Dataset/processed/train_processed/logistic_imputed/logistic_imputed_train_final.csv')
test_data = pd.read_csv('Dataset/processed/train_processed/logistic_imputed/logistic_imputed_test_final.csv')

features = train_data.columns.tolist()
for feature in features:
    if feature_config[feature]['type'] != 'categorical':
        continue
    train_vc = train_data[feature].value_counts()
    test_vc = test_data[feature].value_counts()
    train_unique = train_data[feature].unique()
    test_unique = test_data[feature].unique()
    for tu in test_unique:
        if tu not in train_unique:
            print(f'{feature} {tu} not in train')
            break
    print('-'*100)

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
payer_code 6.7319529594778755 not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
discharge_disposition_id -4.773183079495081 not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
admission_source_id 6.121870231247199 not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
medical_specialty 19.25801622742795 not in train
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------